#!/bin/bash

cd `dirname $0`
mwscript extensions/TrustedXFF/generate.php --wiki=aawiki ../../cache/trusted-xff.cdb
bzip2 -kf ../../cache/trusted-xff.cdb
if [ -x /usr/local/bin/sync-common-file ]; then
	version="`pwd | awk -F/ '{print $5}'`"
	sync-common-file "$version"/cache/trusted-xff.cdb
fi
